### ISSUE TITLE
newProps is undefined

### ISSUE THREAD

**Issue by axelboc** [bespoyasov/react-scroller#7]
- https://github.com/bespoyasov/react-scroller/blob/c306207c3d5916c933bfb652942604779ee53669/dist/index.js#L66
- https://github.com/bespoyasov/react-scroller/blob/c306207c3d5916c933bfb652942604779ee53669/src/react-scroller.js#L39

**Comment by bespoyasov** [comment]
Thanks for your feedback! :–)
